# This file is part of the Ngen - CSIRT Incident Report System.
# 
# (c) CERT UNLP <support@cert.unlp.edu.ar>
# 
# This source file is subject to the GPL v3.0 license that is bundled
# with this source code in the file LICENSE.


cert_ngen_user:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/User/UserFrontendController.php'
    type:     annotation
    prefix:   /users

cert_ngen_user_security:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/User/UserSecurityFrontendController.php'
    type:     annotation
    prefix:   /users
    
cert_ngen_user_security:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/User/UserSecurityFrontendController.php'
    type:     annotation
    prefix:   /users
    
cert_ngen_user_resetting:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/User/UserResettingFrontendController.php'
    type:     annotation
    prefix:   /users/resetting
    
cert_ngen_user_registration:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/User/UserRegistrationFrontendController.php'
    type:     annotation
    prefix:   /users/register
    
cert_ngen_user_profile:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/User/UserProfileFrontendController.php'
    type:     annotation
    prefix:   /users/profile
    
cert_ngen_user_change_password:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/User/UserChangePasswordFrontendController.php'
    type:     annotation
    prefix:   /users/profile

cert_ngen_network_entity:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Network/NetworkEntityFrontendController.php'
    type:     annotation
    prefix:   /networks/entities

cert_ngen_network_admin:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Network/NetworkAdminFrontendController.php'
    type:     annotation
    prefix:   /networks/admins
    
cert_ngen_network:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Network/NetworkFrontendController.php'
    type:     annotation
    prefix:   /networks    
    
cert_ngen_internal_incident:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Incident/InternalIncidentFrontendController.php'
    type:     annotation
    prefix:   /incidents/internals
    
cert_ngen_external_incident:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Incident/ExternalIncidentFrontendController.php'
    type:     annotation
    prefix:   /incidents/externals

cert_ngen_incident_feed:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Incident/IncidentFeedFrontendController.php'
    type:     annotation
    prefix:   /incidents/feeds

cert_ngen_incident_state:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Incident/IncidentStateFrontendController.php'
    type:     annotation
    prefix:   /incidents/states

cert_ngen_incident_type:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Incident/IncidentTypeFrontendController.php'
    type:     annotation
    prefix:   /incidents/types

cert_ngen_incident_type_reports:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Incident/IncidentReportFrontendController.php'
    type:     annotation
    prefix:   /incidents/types
    
cert_ngen_dashboard:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/DashboardController.php'
    type:     annotation
    prefix:   /
    
fos_comment_api:
    type: rest
    resource: '@FOSCommentBundle/Resources/config/routing.yml'
    defaults: { _format: html }

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#    prefix: /


cert_ngen_api:
    type: rest
    prefix: /api
    resource: '@CertUnlpNgenBundle/Resources/config/routing_api.yml'

NelmioApiDocBundle:
    resource: '@NelmioApiDocBundle/Resources/config/routing.yml'
    prefix:   /incidents/api/doc