<?php

namespace CertUnlp\NgenBundle\Entity\Incident\Host\Repository;

/**
 * HostExternalListener
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HostExternalListener extends \Doctrine\ORM\EntityRepository
{
}
