<?php

namespace CertUnlp\NgenBundle\Entity\Incident\Host;

use Doctrine\ORM\EntityRepository;

/**
 * HostRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class HostRepository extends EntityRepository
{
}
